# Biweekly Report 2: Documentation Cont.

## By: Simon Julien (107019123)

### Extending documentation for TensorFlow:

Part of my bi-weekly #1 was developing a detailed documentation of operations, syntax, and functionalities of TensorFlow. As I dive deeper into TensorFlow, I find myself referencing my old report, so I decided to continue this documentation as I come accross it in my development. This can be found below:

In [2]:
import tensorflow as tf #got it installed
print(tf.__version__)

2.6.0


#### Initialization of Tensors

In [2]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32) #specify shape and size
x=tf.constant([[1,2,3],[4,5,6]]) #manual matrix input
x=tf.ones((3,3)) #matrix of ones
x=tf.zeros((2,3)) #matrix of zeros
x=tf.eye(3) #identity matrix

x=tf.random.normal((3,3), mean=0, stddev=1) #random norm dist
x=tf.random.uniform((1,3),minval=0, maxval=1) #random normal


x=tf.range(9) #same as python range func
x=tf.range(start=1, limit=10, delta=2)

x=tf.cast(x,dtype=tf.float64) #cast to new types

print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


#### Mathematical Operations

In [3]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

z=tf.add(x,y) #add elementwise
z=x+y
z=tf.subtract(x,y) #subtract elementwise
z=x-y 

z=tf.divide(x,y) #divide elementwise
z=x/y
z=tf.multiply(x,y) #multiply elementwise
z=x*y

z=tf.tensordot(x,y, axes=1) #dot product
z=tf.reduce_sum(x*y, axis=0)

z=x**5 #exponential

x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y) #matrix multiplication
z=x@y

print(z)

tf.Tensor(
[[ 0.07295457 -0.8626246  -0.34738117 -0.87100303]
 [ 1.0107311  -0.22815785 -0.16178314  0.24419785]], shape=(2, 4), dtype=float32)


#### Indexing

In [4]:
x=tf.constant([0,1,1,2,3,1,2,3])

print(x[:]) #all
print(x[1:]) #truncate
print(x[1:3]) #range
print(x[::2]) #skip 
print(x[::-1]) #reverse order

indices=tf.constant([0,3])
x_ind=tf.gather(x,indices) #grab particular indices
print(x_ind)

x=tf.constant([[1,2],[3,4],[5,6]])
print(x[0,:]) #multiple dimentions
print(x[0:2,:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#### Reshaping

In [9]:
x=tf.range(9)
x=tf.reshape(x,(3,3)) #reshape

x=tf.transpose(x, perm=[1,0]) #transpose
print(x)

x=tf.concat([[1,2],[2,3]], axis=-1) #concatenation
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
tf.Tensor([1 2 2 3], shape=(4,), dtype=int32)
